// This file was initially generated by Windows Terminal 0.11.1191.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "alwaysShowTabs": true,
    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",

    // You can add more global application settings here.
    // To learn more about global settings, visit https://aka.ms/terminal-global-settings

    // If enabled, selections are automatically copied to your clipboard.
    "copyOnSelect": false,

    // If enabled, formatted data is also copied to your clipboard
    "copyFormatting": false,
    "initialCols": 120,
    "initialRows": 30,
    "requestedTheme": "system",
    "showTabsInTitlebar": true,
    "showTerminalTitleInTitlebar": true,
    "tabWidthMode": "equal",
    "snapToGridOnResize": false,
    "wordDelimiters": " /\\()\"'-.,:;<>~!@#$%^&*|+=[]{}~?\u2502",
    "confirmCloseAllTabs": true,
    // A profile specifies a command to execute paired with information about how it should look and feel.
    // Each one of them will appear in the 'New Tab' dropdown,
    //   and can be invoked from the commandline with `wt.exe -p xxx`
    // To learn more about profiles, visit https://aka.ms/terminal-profile-settings
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
            "acrylicOpacity": 0.5,
            "closeOnExit": "graceful",
            "colorScheme": "Vintage",
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "fontFace": "Fira Code Retina",
            "fontSize": 14,
            "historySize": 9001,
            "padding": "8, 8, 8, 8",
            "snapOnInput": true,
            "useAcrylic": true
        },
        "list":
        [
            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell Core",
                "source": "Windows.Terminal.PowershellCore"
            },
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "icon": "ms-appdata:///roaming/ubuntu.png",
                "source": "Windows.Terminal.Wsl"
            },
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },

    // Add custom color schemes to this array.
    // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
    "schemes": 
    [
        {
            "name": "Campbell",
            "foreground": "#CCCCCC",
            "background": "#0C0C0C",
            "black": "#0C0C0C",
            "red": "#C50F1F",
            "green": "#13A10E",
            "yellow": "#C19C00",
            "blue": "#0037DA",
            "purple": "#881798",
            "cyan": "#3A96DD",
            "white": "#CCCCCC",
            "brightBlack": "#767676",
            "brightRed": "#E74856",
            "brightGreen": "#16C60C",
            "brightYellow": "#F9F1A5",
            "brightBlue": "#3B78FF",
            "brightPurple": "#B4009E",
            "brightCyan": "#61D6D6",
            "brightWhite": "#F2F2F2"
        },
        {
            "name": "Campbell Powershell",
            "foreground": "#CCCCCC",
            "background": "#012456",
            "black": "#0C0C0C",
            "red": "#C50F1F",
            "green": "#13A10E",
            "yellow": "#C19C00",
            "blue": "#0037DA",
            "purple": "#881798",
            "cyan": "#3A96DD",
            "white": "#CCCCCC",
            "brightBlack": "#767676",
            "brightRed": "#E74856",
            "brightGreen": "#16C60C",
            "brightYellow": "#F9F1A5",
            "brightBlue": "#3B78FF",
            "brightPurple": "#B4009E",
            "brightCyan": "#61D6D6",
            "brightWhite": "#F2F2F2"
        },
        {
            "name": "Vintage",
            "foreground": "#C0C0C0",
            "background": "#000000",
            "black": "#000000",
            "red": "#800000",
            "green": "#008000",
            "yellow": "#808000",
            "blue": "#000080",
            "purple": "#800080",
            "cyan": "#008080",
            "white": "#C0C0C0",
            "brightBlack": "#808080",
            "brightRed": "#FF0000",
            "brightGreen": "#00FF00",
            "brightYellow": "#FFFF00",
            "brightBlue": "#0000FF",
            "brightPurple": "#FF00FF",
            "brightCyan": "#00FFFF",
            "brightWhite": "#FFFFFF"
        },
        {
            "name": "One Half Dark",
            "foreground": "#DCDFE4",
            "background": "#282C34",
            "black": "#282C34",
            "red": "#E06C75",
            "green": "#98C379",
            "yellow": "#E5C07B",
            "blue": "#61AFEF",
            "purple": "#C678DD",
            "cyan": "#56B6C2",
            "white": "#DCDFE4",
            "brightBlack": "#5A6374",
            "brightRed": "#E06C75",
            "brightGreen": "#98C379",
            "brightYellow": "#E5C07B",
            "brightBlue": "#61AFEF",
            "brightPurple": "#C678DD",
            "brightCyan": "#56B6C2",
            "brightWhite": "#DCDFE4"
        },
        {
            "name": "One Half Light",
            "foreground": "#383A42",
            "background": "#FAFAFA",
            "black": "#383A42",
            "red": "#E45649",
            "green": "#50A14F",
            "yellow": "#C18301",
            "blue": "#0184BC",
            "purple": "#A626A4",
            "cyan": "#0997B3",
            "white": "#FAFAFA",
            "brightBlack": "#4F525D",
            "brightRed": "#DF6C75",
            "brightGreen": "#98C379",
            "brightYellow": "#E4C07A",
            "brightBlue": "#61AFEF",
            "brightPurple": "#C577DD",
            "brightCyan": "#56B5C1",
            "brightWhite": "#FFFFFF"
        },
        {
            "name": "Solarized Dark",
            "foreground": "#839496",
            "background": "#002B36",
            "black": "#073642",
            "red": "#DC322F",
            "green": "#859900",
            "yellow": "#B58900",
            "blue": "#268BD2",
            "purple": "#D33682",
            "cyan": "#2AA198",
            "white": "#EEE8D5",
            "brightBlack": "#002B36",
            "brightRed": "#CB4B16",
            "brightGreen": "#586E75",
            "brightYellow": "#657B83",
            "brightBlue": "#839496",
            "brightPurple": "#6C71C4",
            "brightCyan": "#93A1A1",
            "brightWhite": "#FDF6E3"
        },
        {
            "name": "Solarized Light",
            "foreground": "#657B83",
            "background": "#FDF6E3",
            "black": "#073642",
            "red": "#DC322F",
            "green": "#859900",
            "yellow": "#B58900",
            "blue": "#268BD2",
            "purple": "#D33682",
            "cyan": "#2AA198",
            "white": "#EEE8D5",
            "brightBlack": "#002B36",
            "brightRed": "#CB4B16",
            "brightGreen": "#586E75",
            "brightYellow": "#657B83",
            "brightBlue": "#839496",
            "brightPurple": "#6C71C4",
            "brightCyan": "#93A1A1",
            "brightWhite": "#FDF6E3"
        }
    ],

    // Add custom keybindings to this array.
    // To unbind a key combination from your defaults.json, set the command to "unbound".
    // To learn more about keybindings, visit https://aka.ms/terminal-keybindings
    "keybindings":
    [
        // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
        // These two lines additionally bind them to Ctrl+C and Ctrl+V.
        // To learn more about selection, visit https://aka.ms/terminal-selection
        { "command": "closePane", "keys": [ "ctrl+shift+w" ] },
        { "command": "closeWindow", "keys": [ "alt+f4" ] },
        { "command": "copy", "keys": [ "ctrl+shift+c" ] },
        { "command": "copy", "keys": [ "ctrl+insert" ] },
        { "command": "decreaseFontSize", "keys": [ "ctrl+-" ] },
        // Press Ctrl+Shift+D to open a new pane.
        // - "split": "auto" makes this pane open in the direction that provides the most surface area.
        // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
        // To learn more about panes, visit https://aka.ms/terminal-panes
        { "command": "duplicateTab", "keys": [ "ctrl+shift+d" ] },
        { "command": "increaseFontSize", "keys": [ "ctrl+=" ] },
        { "command": { "action": "moveFocus", "direction": "down" }, "keys": [ "alt+down" ] },
        { "command": { "action": "moveFocus", "direction": "left" }, "keys": [ "alt+left" ] },
        { "command": { "action": "moveFocus", "direction": "right" }, "keys": [ "alt+right" ] },
        { "command": { "action": "moveFocus", "direction": "up" }, "keys": [ "alt+up" ] },
        { "command": "newTab", "keys": [ "ctrl+shift+t" ] },
        { "command": { "action": "newTab", "index": 0 }, "keys": ["ctrl+shift+1"] },
        { "command": { "action": "newTab", "index": 1 }, "keys": ["ctrl+shift+2"] },
        { "command": { "action": "newTab", "index": 2 }, "keys": ["ctrl+shift+3"] },
        { "command": { "action": "newTab", "index": 3 }, "keys": ["ctrl+shift+4"] },
        { "command": { "action": "newTab", "index": 4 }, "keys": ["ctrl+shift+5"] },
        { "command": { "action": "newTab", "index": 5 }, "keys": ["ctrl+shift+6"] },
        { "command": { "action": "newTab", "index": 6 }, "keys": ["ctrl+shift+7"] },
        { "command": { "action": "newTab", "index": 7 }, "keys": ["ctrl+shift+8"] },
        { "command": { "action": "newTab", "index": 8 }, "keys": ["ctrl+shift+9"] },
        { "command": "nextTab", "keys": [ "ctrl+tab" ] },
        { "command": "openNewTabDropdown", "keys": [ "ctrl+shift+space" ] },
        { "command": "openSettings", "keys": [ "ctrl+," ] },
        { "command": "paste", "keys": [ "ctrl+shift+v" ] },
        { "command": "paste", "keys": [ "shift+insert" ] },
        { "command": "prevTab", "keys": [ "ctrl+shift+tab" ] },
        { "command": "resetFontSize", "keys": ["ctrl+0"]},
        { "command": { "action": "resizePane", "direction": "down" }, "keys": [ "alt+shift+down" ] },
        { "command": { "action": "resizePane", "direction": "left" }, "keys": [ "alt+shift+left" ] },
        { "command": { "action": "resizePane", "direction": "right" }, "keys": [ "alt+shift+right" ] },
        { "command": { "action": "resizePane", "direction": "up" }, "keys": [ "alt+shift+up" ] },
        { "command": "scrollDown", "keys": [ "ctrl+shift+down" ] },
        { "command": "scrollDownPage", "keys": [ "ctrl+shift+pgdn" ] },
        { "command": "scrollUp", "keys": [ "ctrl+shift+up" ] },
        { "command": "scrollUpPage", "keys": [ "ctrl+shift+pgup" ] },
        { "command": { "action": "splitPane", "split": "horizontal"}, "keys": [ "alt+shift+-" ] },
        { "command": { "action": "splitPane", "split": "vertical"}, "keys": [ "alt+shift+plus" ] },
        { "command": { "action": "switchToTab", "index": 0 }, "keys": ["ctrl+alt+1"] },
        { "command": { "action": "switchToTab", "index": 1 }, "keys": ["ctrl+alt+2"] },
        { "command": { "action": "switchToTab", "index": 2 }, "keys": ["ctrl+alt+3"] },
        { "command": { "action": "switchToTab", "index": 3 }, "keys": ["ctrl+alt+4"] },
        { "command": { "action": "switchToTab", "index": 4 }, "keys": ["ctrl+alt+5"] },
        { "command": { "action": "switchToTab", "index": 5 }, "keys": ["ctrl+alt+6"] },
        { "command": { "action": "switchToTab", "index": 6 }, "keys": ["ctrl+alt+7"] },
        { "command": { "action": "switchToTab", "index": 7 }, "keys": ["ctrl+alt+8"] },
        { "command": { "action": "switchToTab", "index": 8 }, "keys": ["ctrl+alt+9"] },
        // Press Ctrl+Shift+F to open the search box
        { "command": "find", "keys": [ "ctrl+shift+f" ] },
        { "command": "toggleFullscreen", "keys": [ "alt+enter" ] },
        { "command": "toggleFullscreen", "keys": [ "f11" ] }
    ]
}
